### ISSUE TITLE
hifen vs underscore

### ISSUE THREAD

**Issue by bhargavasana** [osplanning-data-standards/dyno-demand#6]
It might be nice to provide some guidance about when to use '-' or '_'. This is assuming we want to use both. For example, in worker status, we have full-time but then modes have underscore. In purpose, do we want to use work-based or work_based. Currently, I am trying to convert CHTS to dynodemand and thinking about such questions.

**Comment by e-lo** [comment]
Good idea. I think in general, we should use underscores to be consistent with GTFS terminology.  However, full-time, work-based, and Person-trip are all _actually_ hyphened in real-life, which is why we are tempted to have hyphens rather than underscores.  BUT, when to use which could become confusing, so I think we should perhaps default to underscore whenever possible.  

This triggers a change in the variable names for the trip list, which I will update now.

**Comment by e-lo** [comment]
I'll also note that we should continue to use hyphens when discussing modes and separating access and main modes so that they can be parsed.  e.g. walk-commuter_rail-walk
